[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
]

remapings=["@openzeppelin/=lib/openzeppelin-contracts/"]
ffi=true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
